name = "Jankeys' Tensura Reincarnated"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a01e4e48d4469e808845f10af72b94f7741b9dd088bbe8efaafd0dba2806108d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
