smoothMs: 200

barsPercent: 10.0

baseZoomMultiplier: 0.3

minZoomMultiplier: 0.01

maxZoomMultiplier: 1.0

scrollSensitivity: 0.05

hideHudDuringZoom: true

enableCinematicCamera: true

crosshairEffect: true

zoomStartSound: true

zoomStartVolume: 1.0

scrollSound: true

scrollVolume: 1.0

soundVolume: 0.65

screenshotSound: true

screenshotVolume: 1.0

disableEssentialZoom: true

