// Mod sync helper. Mod jars aren't in git, so MODS.md is the tracked record of them.
//   node tools/modlist.js          write MODS.md from CurseForge's minecraftinstance.json (owner/devs adding mods)
//   node tools/modlist.js --check  compare MODS.md with your mods/ folder, print what to install or remove
const fs = require("fs");
const row = (m) => `| ${m.name} | ${m.file} | ${m.url} |`;

if (process.argv.includes("--check")) {
  const listed = fs.readFileSync("MODS.md", "utf8").split("\n").filter((l) => l.startsWith("| ") && l.includes(".jar"))
    .map((l) => l.split("|").map((s) => s.trim()));
  const have = new Set(fs.readdirSync("mods").filter((f) => f.endsWith(".jar")));
  const want = new Set(listed.map((c) => c[2]));
  const missing = listed.filter((c) => !have.has(c[2]));
  const extra = [...have].filter((f) => !want.has(f));
  console.log(`MISSING (install or update these): ${missing.length}`);
  missing.forEach((c) => console.log(`  ${c[1]}  ->  ${c[2]}\n    ${c[3]}`));
  console.log(`EXTRA (not in MODS.md; remove, or ask the owner to add): ${extra.length}`);
  extra.forEach((f) => console.log("  " + f));
} else {
  const inst = JSON.parse(fs.readFileSync("minecraftinstance.json", "utf8"));
  const mods = inst.installedAddons
    .filter((a) => a.isEnabled !== false)
    .map((a) => ({ name: a.name, file: a.installedFile.fileName, url: `${a.webSiteURL}/files/${a.installedFile.id}` }))
    .sort((a, b) => a.name.localeCompare(b.name, "en", { sensitivity: "base" }));
  fs.writeFileSync("MODS.md", [
    "# Mod list",
    "",
    `NeoForge 1.21.1. ${mods.length} mods. Generated by \`node tools/modlist.js\`; do not edit by hand.`,
    "Run `node tools/modlist.js --check` to compare against your own `mods/` folder.",
    "",
    "| Mod | File | Download |",
    "|-----|------|----------|",
    ...mods.map(row),
    "",
  ].join("\n"));
  console.log(`wrote MODS.md (${mods.length} mods)`);
}
